version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8000:8000"  # Exposing backend on localhost:8000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:8000  # Point frontend to backend on localhost
    ports:
      - "3000:3000"  # Exposing frontend on localhost:3000
    networks:
      - app-network
    depends_on:
      - backend  # Ensure frontend waits for backend to be ready

volumes:
  mongo-data: {}

networks:
  app-network:
    driver: bridge
